/**
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser.scoping;

import nl.utwente.ewi.fmt.uppaalSMC.parser.scoping.AbstractUppaalSMCScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class UppaalSMCScopeProvider extends AbstractUppaalSMCScopeProvider {
}
