/*
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser.parser.antlr;

import com.google.inject.Inject;
import nl.utwente.ewi.fmt.uppaalSMC.parser.parser.antlr.internal.InternalUppaalSMCParser;
import nl.utwente.ewi.fmt.uppaalSMC.parser.services.UppaalSMCGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UppaalSMCParser extends AbstractAntlrParser {

	@Inject
	private UppaalSMCGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUppaalSMCParser createParser(XtextTokenStream stream) {
		return new InternalUppaalSMCParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "NSTA";
	}

	public UppaalSMCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UppaalSMCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
