/*
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UppaalSMCStandaloneSetup extends UppaalSMCStandaloneSetupGenerated {

	def static void doSetup() {
		new UppaalSMCStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
