/*
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UppaalSMCRuntimeModule extends AbstractUppaalSMCRuntimeModule {
}
