/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
