/**
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser;

import nl.utwente.ewi.fmt.uppaalSMC.parser.AbstractUppaalSMCRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UppaalSMCRuntimeModule extends AbstractUppaalSMCRuntimeModule {
}
