/**
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser;

import nl.utwente.ewi.fmt.uppaalSMC.parser.UppaalSMCStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UppaalSMCStandaloneSetup extends UppaalSMCStandaloneSetupGenerated {
  public static void doSetup() {
    new UppaalSMCStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
