/**
 * generated by Xtext 2.16.0
 */
package nl.utwente.ewi.fmt.uppaalSMC.parser.validation;

import nl.utwente.ewi.fmt.uppaalSMC.parser.validation.AbstractUppaalSMCValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UppaalSMCValidator extends AbstractUppaalSMCValidator {
}
